### ISSUE TITLE
Two Valid VISA numbers don't work

### ISSUE THREAD

**Issue by BrianWillows** [PawelDecowski/jquery-creditcardvalidator#54] opened 2015-02-26 11:43 UTC
These two VISA numbers are provided as Test card numbers with Authorize.net:

- Visa Test Card: 4007000000027
- Second Visa Test Card: 4012888818888

They're valid according to the PHP Luhn check code

    function is_valid($number) {
      $cardNumber = strrev($number);
      $numSum = 0;

      for ($i=0; $i<strlen($cardNumber); $i++) {
        $currentNum = substr($cardNumber, $i, 1);

// Double every second digit
        if ($i % 2 == 1) {
          $currentNum *= 2;
        }

// Add digits of 2-digit numbers together
        if ($currentNum > 9) {
          $firstNum = $currentNum % 10;
          $secondNum = ($currentNum - $firstNum) / 10;
          $currentNum = $firstNum + $secondNum;
        }

        $numSum += $currentNum;
      }
// If the total has no remainder it's OK
      return ($numSum % 10 == 0);
    }

but not when you try them on http://jquerycreditcardvalidator.com

**Comment by BrianWillows** [comment] 2015-02-26 14:29
http://blog.unibulmerchantservices.com/13-signs-of-a-valid-visa-card/
It seems that some Visa card numbers can be 13 characters starting with a 4

**Comment by PawelDecowski** [comment] 2015-02-26 14:34
Hi Brian. This is a duplicate of #50. Will be fixed in v1.1 coming by the end of March.

Thank you for reporting.

**Closed by PawelDecowski** 2015-02-26 14:34 UTC

**Comment by BrianWillows** [comment] 2015-02-26 14:37
Sorry. Didn't spot that.
I've fixed it for my own version.
Great software by the way.
________________________________
