### ISSUE TITLE
Can't copy and paste code samples from the home page.

### ISSUE THREAD

**Issue by gregkerzhner** [PawelDecowski/jquery-creditcardvalidator#62] opened 2015-07-22 03:59 UTC
Seems like your fancy syntax highlighting is preventing this from happening.  Would be amazing to add some copy and pastable examples to your site, or at least in github.

**Comment by PawelDecowski** [comment] 2015-11-19 10:43
As it turns out, it *is* possible to copy the code samples from the page. The problem is Prism’s (the syntax highlighting plugin) CSS causes the selection to not be visible so you can’t see it, but it’s there.

This is fixed in a newer version of Prism, which I will upgrade to in the next release (by the end of this month).

**Closed** 2016-10-08 19:04 UTC
