### ISSUE TITLE
Clean download JS error

### ISSUE THREAD

**Issue by KevinMcCoy** [PawelDecowski/jquery-creditcardvalidator#69] opened 2015-11-10 17:09 UTC
Uncaught TypeError: Cannot read property 'replace' of undefined - line 188 jquery.creditCardValidator.js

I'm loading: 
jquery-1.11.3.min.js
jquery-ui-1.11.4/jquery-ui.min.js

then loading: 
jquery.creditCardValidator.js

Get an error on that basic setup.

**Comment by PawelDecowski** [comment] 2015-11-18 12:50
Duplicate of #61

**Closed by PawelDecowski** 2015-11-18 12:50 UTC
