### ISSUE TITLE
SOME VALID VISA & DINERS CLUB NUMBERS ARE MARKED AS INVALID

### ISSUE THREAD

**Issue by rojobo** [PawelDecowski/jquery-creditcardvalidator#58] opened 2015-04-20 14:50 UTC
Visa: 4222222222222 *
Diners: 38555565010005 & 38520000023237

*Note : Even though this number has a different character count than the other test numbers, it is the correct and functional number.

Those numbers are valid and the validator will not consider them so.

Thanks.

**Comment by PawelDecowski** [comment] 2015-04-20 14:53
Duplicate of:

* https://github.com/PawelDecowski/jquery-creditcardvalidator/issues/55 and
* https://github.com/PawelDecowski/jquery-creditcardvalidator/pull/50

**Closed by PawelDecowski** 2015-04-20 14:53 UTC
